### ISSUE TITLE
Feature Order Leads to Different Results

### ISSUE THREAD

**Issue by gawainsss** [takuseno/d3rlpy#345] opened 2023-10-20 09:39 UTC
Hello everyone,

I'm working on a debt collection problem using Reinforcement Learning where I aim to determine the optimal collection strategy, including frequency, intensity, and collection methods, to maximize the repayment amount from delinquent clients. I've modelled this as a Markov Decision Process (MDP) based on different types of debts.

Specifically, the state space is represented as a four-dimensional vector corresponding to different debt types: [Credit Card, Micro-loans, Personal Loans, Mortgage]. A sample state like [1,0,0,1] denotes that the repayment percentage for credit card and mortgage is 0%, while there's no overdue for micro-loans and personal loans.

However, I've noticed a peculiar behavior: When I reshuffle the order of the debt types in the state representation, say moving 'Mortgage' to the second position leading to a state like [1,1,0,0], the RL results differ.

Why does changing the order of dimensions/state representation lead to different outcomes? Is there an underlying assumption or behavior in the algorithm that is sensitive to the ordering of state features?

Any insights or advice would be greatly appreciated. Thank you!

**Comment by takuseno** [comment] 2023-10-21 05:35
@gawainsss Thanks for the issue. I believe this is a general RL question, not specific to d3rlpy. I removed `bug` label since this is not a bug report.

From what you mentioned, there are two cases.

1. Train an agent and re-order features at test-time.

Once you train an agent, the agent is capable of making decisions only with the feature order used in training.

2. An agent behaves differently from the other agent trained with different order of features.

Deep learning training has stochasticity (strictly speaking, it can be deterministic, but shaffling features makes different). Thus you might get agents with different behavior every time you train a new agent.


I would suggest you could learn more about neural networks before starting more experiments since this is a very elementary question.

**Comment by takuseno** [comment] 2023-10-21 05:36
Let me close this issue since this is not about d3rlpy.

**Closed by takuseno** 2023-10-21 05:36 UTC

**Comment by gawainsss** [comment] 2023-10-23 01:45
> @gawainsss Thanks for the issue. I believe this is a general RL question, not specific to d3rlpy. I removed `bug` label since this is not a bug report.
> 
> From what you mentioned, there are two cases.
> 
> 1. Train an agent and re-order features at test-time.
> 
> Once you train an agent, the agent is capable of making decisions only with the feature order used in training.
> 
> 2. An agent behaves differently from the other agent trained with different order of features.
> 
> Deep learning training has stochasticity (strictly speaking, it can be deterministic, but shaffling features make difference). Thus you might get agents with different behavior every time you train a new agent.
> 
> I would suggest you could learn more about neural networks before starting more experiments since this is a very elementary question.

Thanks for your answer! Sorry I made a mistake with the label T T
