### ISSUE TITLE
Problem with fine tuning

### ISSUE THREAD

**Issue by lettersfromfelix** [takuseno/d3rlpy#215] opened 2022-08-23 14:20 UTC
Hi takuseno,

Sorry for having to raise another issue, but somehow I can't wrap my head around a problem I experience when trying to fine-tune my custom environment. It consists of a robot capable of 3d movement, which should move in one direction to reach a defined position.
When training it offline, I get awesome results already. Afterwards I wanted to train it online as well to fine-tune it. Unfortunately, in this scenario I experience something weird: 

1. When evaluating (evaluate_on_environment) the offline pre-trained model, I get the same good results as with only offline.
2. When I then execute fit_online, I get really bad results, i.e. the robot moves out of bounds into that direction in which he should move only until a given point) even on the first try in fit_online.
3.  Weirdly when evaluating that algorithm after executing a few fit_online steps (for testing purposes I trained only for 1600 steps, which already lead to 4 terminations due to out of bound), I get the same good result as previously. 

I used the same env instance for the whole procedure. Stuff like action_scaler came to my mind because the direction still is correct (even though it could move in all other directions), but that wouldn't explain why the evaluate_on_environment still works. Do you have any idea what could cause that? Here's my (minimal) code with a few comments:

```
env = CustomEnv() # With 0 randomization for testing purposes
env = TimeLimit(env, max_episode_steps=800)
env.reset()

cql = d3rlpy.algos.CQL.from_json("model_pretrained/params.json")
cql.load_model("model_pretrained/model_2808.pt")
# I used this exact encoder arch for pretraining, every other param of my CQL also is on default
actor_encoder_factory = d3rlpy.models.encoders.VectorEncoderFactory(hidden_units=[300, 400], activation='tanh')
critic_encoder_factory = d3rlpy.models.encoders.VectorEncoderFactory(hidden_units=[300, 400], activation='tanh')
sac = d3rlpy.algos.SAC(use_gpu=False, scaler=cql.scaler, action_scaler=cql.action_scaler, reward_scaler=cql.reward_scaler,  
            actor_learning_rate=0.0000003, # artificially small learning rate to rule out huge updates
            critic_learning_rate=0.0000003, 
            temp_learning_rate=0.0000003,
            actor_encoder_factory=actor_encoder_factory, 
            critic_encoder_factory=critic_encoder_factory,
)
sac.create_impl(cql.observation_shape, cql.action_size)
sac.copy_policy_from(cql)
sac.copy_q_function_from(cql)
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=1000000, env=env)

info = evaluate_on_environment(env, n_trials=1, render=True)(sac)
# This evaluate works perfectly fine with good results, i.e. reaching goal position easily and remain there until time limit 
sac.fit_online(env, buffer, 
        # Within this loop, every iteration of the env gets aborted within the limit (at around 400 steps) because robot reaches env bounds and env is terminated 
        n_steps=1600,
        n_steps_per_epoch=800,
        update_interval=800,      # for debugging to rule out update steps, but same results without these 2 params
        update_start_step=800, # for debugging to rule out update steps, but same results without these 2 params
        timelimit_aware=True,
        
        logdir="/var/tmp/d3rlpy_logs",
        tensorboard_dir="/var/tmp/d3rlpy_tensor")
        
info = evaluate_on_environment(env, n_trials=1, render=True)(sac)
# This evaluate works perfectly fine with good results as well, i.e. reaching goal position easily and remain there until time limit 

```
Upadte: I also tried playing around with the hyper parameters by decreasing the initial_temperature to prevent exploring, increased the batch_size / n_steps to 800 (the time limit in which the goal always was reached), played a little with gamma and tau but nothing really makes a difference. On the first execution of the environment, the robot always moves out of bounds already.

**Comment by takuseno** [comment] 2022-08-24 14:31
Yes, the performance drop for the early fine-tuning steps is often observed in the relevant researches. Please continue fine-tuning steps and compare the training performance from scratch. Alternatively, IQL might show the substantially better fine-tuning performance for some datasets (in this case, you need to use IQL for both pretraining and fine-tuning).
https://d3rlpy.readthedocs.io/en/v1.1.1/references/generated/d3rlpy.algos.IQL.html#d3rlpy.algos.IQL

**Comment by lettersfromfelix** [comment] 2022-08-24 14:46
Thanks for the recommendation, I will definitely try that! 
Nevertheless, shouldn’t the fine tuning still only drop in performance after *something* is learned / explored? In my case, the very first tryout even with the update_start_step being way further isn‘t reaching the target at all and therefore isn‘t even close to the pretrained behavior?

**Comment by takuseno** [comment] 2022-08-24 15:30
Yes, the main cause could be the data distriution shift from offline dataset to online experiences.

Another thing you can try is filling replay buffer with the pretraining dataset, which will slow down the distrobution shift.
https://github.com/takuseno/d3rlpy/blob/672aeced77071349fa172c7a9bd1f418acf16fe6/reproductions/finetuning/iql.py#L61

**Comment by takuseno** [comment] 2022-08-29 11:52
I believe this is the common observation in this research field. Please let me know if you find a way to improve this. It might be a good opportunity for you to advertise your finding since no one knows the best way for this. Since this is not an implementation issue, let me close this.

**Closed by takuseno** 2022-08-29 11:52 UTC

**Comment by lettersfromfelix** [comment] 2022-08-29 11:53
Sure, I‘ll see if I can find anything and will definitely let you know if so! Thanks anyways for helping!

**Comment by wqp89324** [comment] 2024-02-06 21:11
Hello, say I have a policy trained offline, and then I collected some additional data by deploying this policy in the real world. My question is how can I finetune this policy with these new data, because I notice that fit_online method requires an env object that I don't have?
