### ISSUE TITLE
[BUG] When `use_gpu = False` see message "Found no NVIDIA driver on your system"

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#42] opened 2021-01-29 15:31 UTC
Hello @takuseno,

When I use `d3rlpy` on a machine with no GPU and I specify `use_gpu = False` I still see the following warning message
```
/home/user/miniconda3/envs/d3rlpy/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(
(
```
Here is a minimal example that gives the warning
```python
import gym
from d3rlpy.algos import SAC
from d3rlpy.online.buffers import ReplayBuffer

env = gym.make('Pendulum-v0')
sac = SAC(batch_size = 10, use_gpu = False)
buffer = ReplayBuffer(maxlen = 10, env = env)
sac.fit_online(env, buffer, n_steps = 12)
```

**Comment by takuseno** [comment] 2021-01-29 16:30
@pstansell Thank you for sharing your code. With my machines (MacOS, Ubuntu 18.04), this runs fine, and it's not using GPU. And, I googled a bit, there seem to be many cases that this error occurs even with GPU (sounds familiar). But, this is the opposite case. Could you share your environment (OS, CPU, etc)?

**Comment by pstansell** [comment] 2021-01-29 17:00
@takuseno, this is not an important issue for me, so please don't spend much time on it.  However, to answer your questions, I have two laptops that run CentOS Linux release 7.9.2009 (Core).  On both I have used conda to install Python 3.8 and then pip to install the other packages required by d3rlpy. On the machine with a GPU I do not see the warning message, independent of the setting of `use_gpu` to either true or false.  That machine has:
- CPU: Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
- GPU: NVIDIA Corporation GM107GLM [Quadro M1200 Mobile] (rev a2)

The machine without a GPU, which gives the warning, has:
- CPU: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz

In both cases, the version I'm using the following:
```
Python            3.8.0
d3rlpy            0.60
gym               0.18.0
numpy             1.19.5
scikit-learn      0.24.1
scipy             1.6.0
torch             1.7.1
```

**Comment by takuseno** [comment] 2021-01-30 08:52
@pstansell Thanks for sharing additional information. The machine without GPU looks a bit special since I never tried that CPU. I guess this is the issue of PyTorch. I'll update this when the cause is realized. Let me close this issue untile then.

**Closed by takuseno** 2021-01-30 08:52 UTC
Labels: bug
