### ISSUE TITLE
Issue when using d3rlpy.load_learnable() to load trained model

### ISSUE THREAD

**Issue by Zebin-Li** [takuseno/d3rlpy#409] opened 2024-08-16 02:37 UTC
Hi,

I am trying to use `d3rlpy.load_learnable()` to load the trained model, but failed. Below is the error information:
![image](https://github.com/user-attachments/assets/feaa0580-8a3c-44cb-98b2-e90828a1070c)
Can you please guide what I should do about it? Thank you!

**Comment by Zebin-Li** [comment] 2024-08-16 02:58
I was able to use `cql_old.save_model("model.pt");
cql = d3rlpy.algos.CQLConfig().create();
cql.build_with_dataset(dataset)`
to load the model, but when I use the loaded model to perform inference, I met the below issue:
![image](https://github.com/user-attachments/assets/64071f87-cf23-47d1-82bf-d805de16aca9)
Can you please guide where is wrong? Thank you!

**Comment by takuseno** [comment] 2024-08-25 02:18
Sorry for the late response. I imagine that you did as follows:
```
cql_old.save_model("model.pt")
cql = d3rlpy.algos.CQLConfig().create()
cql.build_with_dataset(dataset)
cql.load_model("model.pt")
```
I think this looks reasonble. The error seems complain that preprocessors are not built. But, `build_with_dataset` is supposed to do that. If you give me more lines of your codes, it helps me to identify the cause.

**Comment by takuseno** [comment] 2024-09-14 04:31
Let me close this issue since the above example should resolve the issue. Feel free to reopen this if there is any further discussion.

**Closed by takuseno** 2024-09-14 04:31 UTC
Labels: bug
