### ISSUE TITLE
'smaller is better' in discounted_sum_of_advantage_scorer function

### ISSUE THREAD

**Issue by GeneLiuXe** [takuseno/d3rlpy#99] opened 2021-07-21 13:18 UTC
**Describe the bug**
Why did the doc here(https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/metrics/scorer.py#L172) say that 'smaller is better'?

**Comment by takuseno** [comment] 2021-07-23 06:55
@GeneLiuXe Hi, thanks for the issue. I believe this is not a bug issue. The equation is as follows.
![image](https://user-images.githubusercontent.com/5235131/126745961-da8658b4-e8a9-4d96-ab24-c3213a8ab43d.png)

This computes the difference between `Q-values for dataset actions` and `Q-values for the policy actions`. If the policy actions have the larger Q-values, the result will be negative value.

**Comment by GeneLiuXe** [comment] 2021-07-23 07:06
Hey, thanks for the reply. You define the `advantages` equal to `Q-values for dataset actions` minus `Q-values for the policy actions` here (https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/metrics/scorer.py#L161), but return `the negative advantages` (https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/metrics/scorer.py#L173). So 'bigger is better'?

**Comment by takuseno** [comment] 2021-07-23 07:09
No. This means just `negative values are smaller than positive values`. The smaller output of this scorer function suggests better performance.

**Comment by takuseno** [comment] 2021-07-23 07:11
Ah, sorry. The comment explains why we add a negative sign at the end. So the bigger output of this scorer function suggests better performance.

**Comment by GeneLiuXe** [comment] 2021-07-23 07:13
Thanks, you verify my idea.

**Comment by takuseno** [comment] 2021-07-23 09:14
But, please note that the recorded values will be multiplied by `-1`, which means that the smaller recorded values suggest better performance.

**Comment by takuseno** [comment] 2021-08-04 09:13
Let me close this since we don't have active discussions in this issue. Please feel free to reopen this, if you have something to discuss.

**Closed by takuseno** 2021-08-04 09:13 UTC
Labels: question
