### ISSUE TITLE
[REQUEST] Offline Reproduction of AWR

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#154] opened 2021-12-15 17:00 UTC
Hello,

thanks a lot for your work. I wanna to reproduce the result of AWR, however, it seems there is no implementation in ./reproductions/offlines/ folder. Would you like to add reproduce of AWR algorithm?

Thanks a lot

**Comment by takuseno** [comment] 2021-12-16 11:10
Hello, thanks for the issue. Unfortunately, AWR reproduction is not planned and AWR will be dropped in the future because it has a slightly different training scheme and is less powerful than the other methods. Most importantly, AWR is not really used in recent papers.  Sorry about the inconvenience.

**Comment by takuseno** [comment] 2022-01-01 01:21
Let me close this issue for now.

**Closed by takuseno** 2022-01-01 01:21 UTC
Labels: enhancement
